apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vault-test
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/Burakhan/argocd-test-vault.git
    targetRevision: HEAD
    path: path/to/your/app
    plugin:
      name: argocd-vault-plugin
  destination:
    server: https://kubernetes.default.svc
    namespace: vault-test
  syncPolicy:
    automated:
      prune: true
      selfHeal: true 